### ISSUE TITLE
Avoid force-push to master if possible

### ISSUE THREAD

**Issue by pchaigno** [amclain/sublime-netlinx#9]
We have a reference to this repository in [github/linguist](https://github.com/github/linguist), as this grammar is used on github.com to highlight code.

Your submodule points to a109318915751ff318de4b4d3bfc34ee57cec921:
```
commit a109318915751ff318de4b4d3bfc34ee57cec921
Author: Alex McLain <alex@alexmclain.com>
Date:   Thu May 7 11:30:05 2015 -0700

    Added package control link to readme.
    Updated Vintage plugin to Vintageous.
```
This commit id doesn't exist anymore on your master branch. I'm guessing this is because you force-pushed and rewrote the git commit history. As a result, the CI build of github/linguist is broken. That's not a big issue, but it can be a bit annoying.

I don't know if it was intentional or if it was a mistake. In any case, could you avoid rewriting your master branch's commit history? Other repositories may rely on it.

**Comment by amclain** [comment]
Yes, this was intentional. I was unfortunately forced to overwrite `master` due to an issue with corruption; I'm well aware it's not good practice. I checked the linguist [`.gitmodules`](https://github.com/github/linguist/blob/master/.gitmodules#L498) before doing this and only saw `url = https://github.com/amclain/sublime-netlinx` with no reference to the commit history, so I was hoping this would have been acceptable to push out a quick fix for your request in #8.

Are you handling the update to linguist or do you need me to do that?

**Comment by amclain** [comment]
I should also note that I was updating the submodules with the following to run the linguist grammar compiler and it was working fine:

```text
git submodule update --recursive --remote
```

The git community tends to frown upon submodules due to issues like this that can happen with them. Considering linguist has a bootstrap script, it may be worth considering running `git clone` over the list of third-party repos instead of relying on submodules. It seems like that would help to decouple the third-party components from the linguist repo history. Just something to think about.

**Comment by pchaigno** [comment]
Thanks for the explanation! :-)

> Are you handling the update to linguist or do you need me to do that?

I'll handle it.
